#!/usr/bin/env python3
"""
dashboard/streamlit_app.py
Streamlit nurse-station dashboard for the AI Ambient Stethoscope simulator.

Run with::

    streamlit run dashboard/streamlit_app.py --server.port 8501

Features
--------
- Live per-room status grid (risk score, vital signs, alert level)
- Trend charts for breath rate, cough rate, SpO₂, temperature
- "Simulate Deterioration" / "Restore Normal" buttons per room
- Active alerts panel with acknowledge buttons
- Auto-refresh every 3 seconds via st.rerun()
"""

from __future__ import annotations

import csv
import os
import sys
import tempfile
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests
import streamlit as st

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from shared.config import BACKEND_API_URL, ROOM_IDS
from shared.constants import RISK_COLORS, SEVERITY_EMOJI

SCENARIO_LABELS = {
    "normal": "Normal",
    "deteriorating": "Deteriorating",
    "pneumonia_like": "Pneumonia-like",
    "uri_like": "URI-like",
    "sleep_apnea_like": "Sleep-apnea-like",
}

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="HAP Monitor – Nurse Dashboard",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="collapsed",
)

_API = BACKEND_API_URL.rstrip("/")
_DEFAULT_AUDIO_MODEL = str(Path(_REPO_ROOT) / "models" / "respiratory_event_model.joblib")
_DEFAULT_MANIFEST = str(Path(_REPO_ROOT) / "datasets" / "real_audio_manifest.csv")

pause_refresh = st.sidebar.toggle(
    "Pause auto-refresh (for audio analysis)",
    value=st.session_state.get("pause_refresh", False),
)
st.session_state["pause_refresh"] = pause_refresh

if "audio_model_path" not in st.session_state:
    st.session_state["audio_model_path"] = _DEFAULT_AUDIO_MODEL
if "dataset_manifest_path" not in st.session_state:
    st.session_state["dataset_manifest_path"] = _DEFAULT_MANIFEST
if "isolation_model_path" not in st.session_state:
    st.session_state["isolation_model_path"] = st.session_state["audio_model_path"]

st.sidebar.text_input(
    "Audio model path",
    key="audio_model_path",
    help="Used for disease prediction and respiratory-event extraction.",
)
st.sidebar.text_input(
    "Dataset test manifest path",
    key="dataset_manifest_path",
    help="CSV generated by scripts/build_real_audio_manifest.py",
)

# ── Helpers ───────────────────────────────────────────────────────────────────

def _get(path: str, default: Any = None) -> Any:
    try:
        r = requests.get(f"{_API}{path}", timeout=3)
        r.raise_for_status()
        return r.json()
    except Exception:
        return default


def _post(path: str, json: dict = None) -> bool:
    try:
        r = requests.post(f"{_API}{path}", json=json or {}, timeout=3)
        return r.ok
    except Exception:
        return False


def _risk_color(level: str) -> str:
    return RISK_COLORS.get(level, "#95a5a6")


def _level_badge(level: str) -> str:
    labels = {
        "normal": "🟢 Normal",
        "medium": "🟡 Medium",
        "high": "🟠 High",
        "critical": "🔴 Critical",
    }
    return labels.get(level, level)


def _sparkline_data(ts_rows: List[Dict], field: str) -> List[float]:
    return [r.get(field, 0) for r in ts_rows]


@st.cache_data(ttl=60)
def _load_sample_index(manifest_csv: str) -> Dict[str, List[str]]:
    out: Dict[str, List[str]] = {}
    if not manifest_csv or not os.path.exists(manifest_csv):
        return out
    with open(manifest_csv, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            path = (row.get("audio_path") or "").strip()
            label = (row.get("label") or "").strip().lower()
            if not path or not label:
                continue
            if not os.path.exists(path):
                continue
            out.setdefault(label, [])
            if path not in out[label]:
                out[label].append(path)
    for label in out:
        out[label] = sorted(out[label])
    return out


def _sample_label_for_scenario(scenario: str) -> str:
    if scenario in {"pneumonia_like", "deteriorating"}:
        return "crackle"
    if scenario == "uri_like":
        return "cough"
    if scenario == "sleep_apnea_like":
        return "wheeze"
    return "ambient"


def _to_audio_bytes(path: str) -> bytes:
    with open(path, "rb") as f:
        return f.read()


# ── Header ────────────────────────────────────────────────────────────────────
st.markdown(
    """
    <div style='background:#1a2a3a;padding:18px 24px;border-radius:8px;margin-bottom:12px'>
      <h1 style='color:white;margin:0;font-size:1.6rem'>
        🏥 AI-Powered Ambient Stethoscope – Nurse Dashboard
      </h1>
      <p style='color:#adb5bd;margin:4px 0 0'>
        Privacy-preserving HAP detection · Features only · No audio stored
      </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# ── Ward summary bar ──────────────────────────────────────────────────────────
summary = _get("/summary", {})
c1, c2, c3, c4 = st.columns(4)
c1.metric("Total Rooms", summary.get("total_rooms", len(ROOM_IDS)))
c2.metric("🔴 Critical", summary.get("critical_rooms", 0))
c3.metric("🟠 High Risk", summary.get("high_risk_rooms", 0))
c4.metric("🔔 Active Alerts", summary.get("total_active_alerts", 0))

st.divider()

# ── Active alerts panel ───────────────────────────────────────────────────────
with st.expander("🔔 Active Alerts", expanded=True):
    alerts: List[Dict] = _get("/alerts", [])
    if not alerts:
        st.success("No active alerts – all rooms nominal.")
    else:
        for a in alerts:
            sev = a.get("severity", "medium")
            emoji = SEVERITY_EMOJI.get(sev, "🔔")
            col_a, col_b = st.columns([9, 1])
            with col_a:
                st.markdown(
                    f"<div style='background:{_risk_color(sev if sev != 'medium' else 'medium')}20;"
                    f"border-left:4px solid {_risk_color(sev if sev != 'medium' else 'medium')};"
                    f"padding:8px 12px;border-radius:4px;margin:4px 0'>"
                    f"{emoji} <b>Room {a['room_id']}</b> &nbsp;|&nbsp; "
                    f"{a.get('message','')} "
                    f"<small style='color:#666'>({a.get('timestamp','')[:19]})</small>"
                    f"</div>",
                    unsafe_allow_html=True,
                )
            with col_b:
                if st.button("✓ Ack", key=f"ack_{a['id']}"):
                    ok = _post(
                        f"/alerts/{a['id']}/acknowledge",
                        {"acknowledged_by": "nurse_dashboard"},
                    )
                    if ok:
                        st.rerun()
                    else:
                        st.error(
                            f"Failed to acknowledge alert #{a['id']}. "
                            "Please verify backend connectivity."
                        )

st.divider()

# ── Room grid ─────────────────────────────────────────────────────────────────
st.subheader("📊 Room Status Grid")
sample_index = _load_sample_index(st.session_state.get("dataset_manifest_path", ""))
available_sample_labels = sorted(sample_index.keys())
COLS = 3
grid_cols = st.columns(COLS)

for idx, room_id in enumerate(ROOM_IDS):
    col = grid_cols[idx % COLS]
    with col:
        status: Dict = _get(f"/rooms/{room_id}/status", {})
        level = status.get("alert_level", "normal")
        risk = status.get("risk_score", 0.0)
        br = status.get("breath_rate_bpm", 0.0)
        cpm = status.get("coughs_per_min", 0.0)
        spm = status.get("sneezes_per_min", 0.0)
        snpm = status.get("snores_per_min", 0.0)
        spo2 = status.get("spo2_pct", 0.0)
        temp = status.get("temperature_c", 0.0)
        scenario = status.get("scenario", "normal")
        likely_disease = status.get("likely_disease", "none")
        disease_probs = status.get("disease_probabilities", {})

        border = _risk_color(level)
        st.markdown(
            f"""<div style='border:2px solid {border};border-radius:8px;
            padding:12px;margin-bottom:8px'>
            <h3 style='margin:0 0 6px;color:{border}'>
              Room {room_id} &nbsp; {_level_badge(level)}
            </h3>
            <table style='width:100%;font-size:.9rem'>
              <tr><td>🫁 Breath Rate</td><td><b>{br:.1f} bpm</b></td></tr>
              <tr><td>💨 Coughs/min</td><td><b>{cpm:.1f}</b></td></tr>
              <tr><td>🤧 Sneezes/min</td><td><b>{spm:.1f}</b></td></tr>
              <tr><td>😴 Snores/min</td><td><b>{snpm:.1f}</b></td></tr>
              <tr><td>🩸 SpO₂</td>       <td><b>{spo2:.1f}%</b></td></tr>
              <tr><td>🌡 Temperature</td><td><b>{temp:.1f}°C</b></td></tr>
              <tr><td>📊 Risk Score</td> <td><b>{risk:.2f}</b></td></tr>
              <tr><td>🧪 Likely Disease</td><td><b>{likely_disease.replace('_',' ').title()}</b></td></tr>
            </table>
            </div>""",
            unsafe_allow_html=True,
        )
        if disease_probs:
            st.caption(
                "Probabilities: "
                + " · ".join(
                    f"{k.replace('_', ' ').title()} {v:.0%}"
                    for k, v in disease_probs.items()
                )
            )

        # Scenario control buttons
        selected_scenario = st.selectbox(
            "Scenario",
            options=list(SCENARIO_LABELS.keys()),
            index=max(list(SCENARIO_LABELS.keys()).index(scenario), 0)
            if scenario in SCENARIO_LABELS
            else 0,
            format_func=lambda v: SCENARIO_LABELS.get(v, v),
            key=f"scenario_select_{room_id}",
        )

        default_sample_label = _sample_label_for_scenario(selected_scenario)
        if default_sample_label not in available_sample_labels and available_sample_labels:
            default_sample_label = available_sample_labels[0]
        sample_label = st.selectbox(
            "Dataset test sample label",
            options=available_sample_labels or ["ambient"],
            index=available_sample_labels.index(default_sample_label)
            if default_sample_label in available_sample_labels
            else 0,
            key=f"sample_label_{room_id}",
        )

        room_samples = sample_index.get(sample_label, [])[:40]
        selected_sample = st.selectbox(
            "Dataset test sample",
            options=room_samples,
            format_func=lambda p: f"{Path(p).name} ({Path(p).parent.name})",
            key=f"sample_path_{room_id}",
        ) if room_samples else None

        btn_col1, btn_col2, btn_col3 = st.columns(3)
        with btn_col1:
            if st.button(
                "Apply",
                key=f"scenario_apply_{room_id}",
                use_container_width=True,
            ):
                ok = _post(
                    f"/rooms/{room_id}/scenario",
                    {"room_id": room_id, "scenario": selected_scenario},
                )
                if ok:
                    st.rerun()
                else:
                    st.error(f"Failed to apply scenario for room {room_id}.")
        with btn_col2:
            if st.button(
                "Deteriorate + Predict",
                key=f"deteriorate_predict_{room_id}",
                use_container_width=True,
            ):
                ok = _post(
                    f"/rooms/{room_id}/scenario",
                    {"room_id": room_id, "scenario": "deteriorating"},
                )
                if not ok:
                    st.error(f"Failed to set room {room_id} to deteriorating.")
                elif not selected_sample:
                    st.warning("No dataset sample is available for this label.")
                else:
                    try:
                        from edge_ml.real_audio import infer_disease_from_audio, isolate_patient_sounds

                        tmp_out = tempfile.NamedTemporaryFile(delete=False, suffix=".wav")
                        tmp_out.close()

                        model_for_use = st.session_state.get("audio_model_path", "")
                        if not model_for_use or not os.path.exists(model_for_use):
                            model_for_use = None

                        pred = infer_disease_from_audio(
                            audio_path=selected_sample,
                            model_path=model_for_use,
                        )
                        iso = isolate_patient_sounds(
                            input_audio_path=selected_sample,
                            output_audio_path=tmp_out.name,
                            model_path=model_for_use,
                            target_labels=("cough", "sneeze", "crackle", "wheeze"),
                        )
                        st.session_state[f"room_audio_review_{room_id}"] = {
                            "sample_path": selected_sample,
                            "sample_label": sample_label,
                            "raw_audio": _to_audio_bytes(selected_sample),
                            "filtered_audio": _to_audio_bytes(tmp_out.name),
                            "prediction": pred,
                            "isolation": iso,
                            "updated_at": datetime.now().strftime("%H:%M:%S"),
                        }
                        st.success("Deterioration triggered and disease prediction completed.")
                        st.rerun()
                    except Exception as exc:  # noqa: BLE001
                        st.error(f"Prediction failed for room {room_id}: {exc}")
        with btn_col3:
            if st.button(
                "Restore Normal",
                key=f"norm_{room_id}",
                disabled=scenario == "normal",
                use_container_width=True,
            ):
                ok = _post(
                    f"/rooms/{room_id}/scenario",
                    {"room_id": room_id, "scenario": "normal"},
                )
                if ok:
                    st.rerun()
                else:
                    st.error(f"Failed to restore room {room_id} to normal.")

        playback_col1, playback_col2 = st.columns(2)
        with playback_col1:
            if st.button("Play sample", key=f"play_raw_{room_id}", use_container_width=True):
                if selected_sample and os.path.exists(selected_sample):
                    st.session_state[f"room_audio_manual_{room_id}"] = {
                        "sample_path": selected_sample,
                        "raw_audio": _to_audio_bytes(selected_sample),
                    }
                else:
                    st.warning("Selected sample file is not available.")
        with playback_col2:
            if st.button("Play filtered", key=f"play_filtered_{room_id}", use_container_width=True):
                review = st.session_state.get(f"room_audio_review_{room_id}", {})
                if not review.get("filtered_audio"):
                    st.info("Run Deteriorate + Predict first to generate filtered audio.")

        manual_play = st.session_state.get(f"room_audio_manual_{room_id}", {})
        if manual_play.get("raw_audio"):
            st.caption("Dataset sample audio")
            st.audio(manual_play["raw_audio"], format="audio/wav")

        review = st.session_state.get(f"room_audio_review_{room_id}", {})
        if review:
            pred = review.get("prediction", {})
            iso = review.get("isolation", {})
            st.markdown(
                "**Audio Disease Prediction**"
                f"  \nLikely disease: **{str(pred.get('likely_disease', 'unknown')).replace('_', ' ').title()}**"
                f"  \nUpdated: {review.get('updated_at', '')}"
            )
            disease_probs = pred.get("disease_probabilities", {})
            if disease_probs:
                st.caption(
                    "Disease probabilities: "
                    + " · ".join(
                        f"{k.replace('_', ' ').title()} {v:.0%}"
                        for k, v in disease_probs.items()
                    )
                )
            event_probs = pred.get("event_probabilities", {})
            if event_probs:
                st.caption(
                    "Event probabilities: "
                    + " · ".join(
                        f"{k.title()} {v:.0%}" for k, v in event_probs.items()
                    )
                )
            st.caption(
                f"Conversation removal: kept {iso.get('kept_windows', 0)}"
                f" / {iso.get('total_windows', 0)} windows"
            )
            if review.get("raw_audio"):
                st.caption("Raw room sample audio")
                st.audio(review["raw_audio"], format="audio/wav")
            if review.get("filtered_audio"):
                st.caption("Filtered respiratory-only audio")
                st.audio(review["filtered_audio"], format="audio/wav")

st.divider()

# ── Trend charts ──────────────────────────────────────────────────────────────
st.subheader("📈 Trend Charts")
selected_room = st.selectbox("Select room for detailed trends", ROOM_IDS)

ts_rows: List[Dict] = _get(f"/rooms/{selected_room}/timeseries?limit=120", [])

if ts_rows:
    import pandas as pd

    df = pd.DataFrame(ts_rows)
    # Ensure timestamp column
    if "timestamp" in df.columns:
        df["timestamp"] = pd.to_datetime(df["timestamp"])
        df = df.set_index("timestamp").sort_index()

    chart_cols = st.columns(2)
    with chart_cols[0]:
        st.markdown("**🫁 Breathing Rate (bpm)**")
        if "breath_rate_bpm" in df.columns:
            st.line_chart(df["breath_rate_bpm"])
        st.markdown("**💨 Coughs per Minute**")
        if "coughs_per_min" in df.columns:
            st.area_chart(df["coughs_per_min"])
    with chart_cols[1]:
        st.markdown("**🩸 SpO₂ (%)**")
        if "spo2_pct" in df.columns:
            st.line_chart(df["spo2_pct"])
        st.markdown("**📊 Anomaly Score**")
        if "anomaly_score" in df.columns:
            st.area_chart(df["anomaly_score"])
else:
    st.info("No timeseries data yet – start the sensor simulator.")

st.divider()

# ── Patient sound isolation ──────────────────────────────────────────────────
st.subheader("Audio Isolation (Cough/Sneeze/Crackle/Wheeze)")
st.caption(
    "Upload a recording to remove likely conversations/background and keep "
    "respiratory event sounds only."
)

uploaded_audio = st.file_uploader(
    "Upload audio clip",
    type=["wav", "ogg", "webm", "mp3", "m4a"],
)
target_labels = st.multiselect(
    "Events to keep",
    options=["cough", "sneeze", "crackle", "wheeze"],
    default=["cough", "sneeze", "crackle", "wheeze"],
)
model_path = st.text_input(
    "Model path (optional)",
    key="isolation_model_path",
    help="Use scripts/train_real_audio_model.py to train a custom model.",
)

if uploaded_audio and st.button("Extract patient-only sounds", use_container_width=False):
    if not target_labels:
        st.warning("Select at least one target event.")
    else:
        try:
            from edge_ml.real_audio import isolate_patient_sounds

            suffix = Path(uploaded_audio.name).suffix or ".wav"
            tmp_in = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
            tmp_out = tempfile.NamedTemporaryFile(delete=False, suffix=".wav")
            tmp_in.write(uploaded_audio.getvalue())
            tmp_in.flush()
            tmp_in.close()
            tmp_out.close()

            model_for_use = model_path if os.path.exists(model_path) else None
            result = isolate_patient_sounds(
                input_audio_path=tmp_in.name,
                output_audio_path=tmp_out.name,
                model_path=model_for_use,
                target_labels=target_labels,
            )

            st.success(
                f"Kept {result['kept_windows']} windows out of "
                f"{result['total_windows']} windows."
            )
            with open(tmp_out.name, "rb") as f:
                cleaned_audio = f.read()
            st.audio(cleaned_audio, format="audio/wav")
            st.download_button(
                "Download cleaned respiratory audio",
                data=cleaned_audio,
                file_name="patient_respiratory_events.wav",
                mime="audio/wav",
            )
        except Exception as exc:  # noqa: BLE001
            st.error(f"Audio isolation failed: {exc}")

# ── Auto-refresh ──────────────────────────────────────────────────────────────
st.caption(
    f"🔄 Auto-refreshing every 3 s · Last update: {datetime.now().strftime('%H:%M:%S')}"
)
if not st.session_state.get("pause_refresh", False):
    time.sleep(3)
    st.rerun()
